pipeline:
  name: testing
  identifier: testing
  projectIdentifier: harness_build_testing
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: jangamsetty
        repoName: google-search-page
        build: <+input>
  stages:
    - stage:
        name: building
        identifier: building
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: npm run build
